package main

type Affiliate struct {
	Id    int    `json:"id"`
	Name  string `json:"name"`
	Token string `json:"token"`
}

type Publication struct {
	UID         int    `json:"id"`
	Name        string `json:"name"`
	AffiliateId int    `json:"affiliateid"`
	Type        string `json:"type"`
	Data        PublicationDetail
}

type PublicationDetail struct {
	ID                            string        `json:"$id"`
	Name                          string        `json:"Name"`
	EditorName                    string        `json:"EditorName"`
	UseIntradayData               bool          `json:"UseIntradayData"`
	Notes                         interface{}   `json:"Notes"`
	AdminName                     string        `json:"AdminName"`
	AdminEmail                    string        `json:"AdminEmail"`
	SecondEmail                   interface{}   `json:"SecondEmail"`
	ThirdEmail                    interface{}   `json:"ThirdEmail"`
	ReceiveEmailAlerts            bool          `json:"ReceiveEmailAlerts"`
	IsDrip                        bool          `json:"IsDrip"`
	AdjustBySplit                 bool          `json:"AdjustBySplit"`
	DisplayIndex                  int           `json:"DisplayIndex"`
	LastUpdateDate                string        `json:"LastUpdateDate"`
	ReturnOnInvestments           []interface{} `json:"ReturnOnInvestments"`
	IsSpecialPortfolio            bool          `json:"IsSpecialPortfolio"`
	Cash                          float64       `json:"Cash"`
	InitialCash                   float64       `json:"InitialCash"`
	DateUpdate                    string        `json:"DateUpdate"`
	CalendarX                     int           `json:"CalendarX"`
	Quantity                      int           `json:"Quantity"`
	PercentWins                   float64       `json:"PercentWins"`
	BiggestWinner                 float64       `json:"BiggestWinner"`
	BiggestLoser                  float64       `json:"BiggestLoser"`
	AvgGain                       float64       `json:"AvgGain"`
	MonthAvgGain                  float64       `json:"MonthAvgGain"`
	QuarterAvgGain                float64       `json:"QuarterAvgGain"`
	HalfAvgGain                   float64       `json:"HalfAvgGain"`
	YearAvgGain                   float64       `json:"YearAvgGain"`
	AvgHold                       float64       `json:"AvgHold"`
	PortfolioValue                float64       `json:"PortfolioValue"`
	OpenQuantity                  int           `json:"OpenQuantity"`
	OpenAvgGain                   float64       `json:"OpenAvgGain"`
	OpenMonthAvgGain              float64       `json:"OpenMonthAvgGain"`
	OpenQuarterAvgGain            float64       `json:"OpenQuarterAvgGain"`
	OpenHalfAvgGain               float64       `json:"OpenHalfAvgGain"`
	OpenYearAvgGain               float64       `json:"OpenYearAvgGain"`
	OpenAvgHold                   float64       `json:"OpenAvgHold"`
	CloseAvgHold                  float64       `json:"CloseAvgHold"`
	CloseYearAvgGain              float64       `json:"CloseYearAvgGain"`
	CloseHalfAvgGain              float64       `json:"CloseHalfAvgGain"`
	CloseQuarterAvgGain           float64       `json:"CloseQuarterAvgGain"`
	CloseMonthAvgGain             float64       `json:"CloseMonthAvgGain"`
	CloseAvgGain                  float64       `json:"CloseAvgGain"`
	CloseQuantity                 int           `json:"CloseQuantity"`
	AverageCapitalGainsYield      float64       `json:"AverageCapitalGainsYield"`
	ShowPortfolioInPreviewAllList bool          `json:"ShowPortfolioInPreviewAllList"`
	BusinessUnit                  interface{}   `json:"BusinessUnit"`
	PubCode                       struct {
		Id          string `json:"$id"`
		PubCode     string `json:"PubCode"`
		PubTitle    string `json:"PubTitle"`
		PubCategory string `json:"PubCategory"`
		Idpc        int    `json:"Id"`
	} `json:"PubCode"`
	InitialDate          string      `json:"InitialDate"`
	InitialOpenDate      string      `json:"InitialOpenDate"`
	InitialCloseDate     string      `json:"InitialCloseDate"`
	InitialPublishDate   string      `json:"InitialPublishDate"`
	InitialUnPublishDate string      `json:"InitialUnPublishDate"`
	AvailableCash        float64     `json:"AvailableCash"`
	CurrencyType         interface{} `json:"CurrencyType"`
	PublisherID          int         `json:"PublisherId"`
	IDx                  int         `json:"Id"`
}

type PositionDetail struct {
	ID         string `json:"$id"`
	TradeGroup struct {
		Id              string `json:"$id"`
		Name            string `json:"Name"`
		TradeGroupOrder int    `json:"TradeGroupOrder"`
		Idtg            int    `json:"Id"`
	} `json:"TradeGroup"`
	PositionSetting struct {
		Id                        string      `json:"$id"`
		Published                 bool        `json:"Published"`
		OpenPriceLink             string      `json:"OpenPriceLink"`
		AutoOpenPriceLink         string      `json:"AutoOpenPriceLink"`
		OpenDateLink              string      `json:"OpenDateLink"`
		ClosePriceLink            string      `json:"ClosePriceLink"`
		CloseDateLink             interface{} `json:"CloseDateLink"`
		EditorOpen                string      `json:"EditorOpen"`
		EditorClose               string      `json:"EditorClose"`
		MaxDownSide               interface{} `json:"MaxDownSide"`
		SymbolLink                interface{} `json:"SymbolLink"`
		Text1                     interface{} `json:"Text1"`
		Text2                     string      `json:"Text2"`
		Text3                     interface{} `json:"Text3"`
		Text4                     interface{} `json:"Text4"`
		Text5                     interface{} `json:"Text5"`
		ReasonForPublish          string      `json:"ReasonForPublish"`
		ReasonForCustomSymbol     string      `json:"ReasonForCustomSymbol"`
		ReasonForDRiP             string      `json:"ReasonForDRiP"`
		ReasonForCustomOpenPrice  string      `json:"ReasonForCustomOpenPrice"`
		ReasonForCustomClosePrice string      `json:"ReasonForCustomClosePrice"`
		ApprovedBuy               bool        `json:"ApprovedBuy"`
		ApprovedSell              bool        `json:"ApprovedSell"`
		OpenApprovedStatus        int         `json:"OpenApprovedStatus"`
		CloseApprovedStatus       int         `json:"CloseApprovedStatus"`
		LegalApproverBuy          string      `json:"LegalApproverBuy"`
		LegalApproverSell         interface{} `json:"LegalApproverSell"`
		LegalNotes                string      `json:"LegalNotes"`
		IsDelisted                bool        `json:"IsDelisted"`
		Editor                    interface{} `json:"Editor"`
		Recommend                 interface{} `json:"Recommend"`
		TrailingStop              interface{} `json:"TrailingStop"`
		HardStop                  interface{} `json:"HardStop"`
		CloseBelowStop            interface{} `json:"CloseBelowStop"`
		CloseAboveStop            interface{} `json:"CloseAboveStop"`
		StopPriority              interface{} `json:"StopPriority"`
		StopPriorityValue         string      `json:"StopPriorityValue"`
		StopPriceValue            string      `json:"StopPriceValue"`
		IsNewBuy                  bool        `json:"IsNewBuy"`
		IsNewSell                 bool        `json:"IsNewSell"`
		IsTopFive                 bool        `json:"IsTopFive"`
		Idps                      int         `json:"Id"`
	} `json:"PositionSetting"`
	CustomSymbol           interface{} `json:"CustomSymbol"`
	CurrencyType           int         `json:"CurrencyType"`
	PositionApprovedStatus int         `json:"PositionApprovedStatus"`
	CurrencyName           string      `json:"CurrencyName"`
	Strategy               int         `json:"Strategy"`
	CurrencySygn           string      `json:"CurrencySygn"`
	CurrencyPattern        string      `json:"CurrencyPattern"`
	CurrentCurrencyType    int         `json:"CurrentCurrencyType"`
	PositionContent        []struct {
		Id          string `json:"$id"`
		FileName    string `json:"FileName"`
		ContentType int    `json:"ContentType"`
		Idpc        int    `json:"Id"`
	} `json:"PositionContent"`
	PositionType                int         `json:"PositionType"`
	Name                        string      `json:"Name"`
	Symbol                      string      `json:"Symbol"`
	SymbolID                    int         `json:"SymbolId"`
	IsCustomSymbol              interface{} `json:"IsCustomSymbol"`
	PortfolioID                 int         `json:"PortfolioId"`
	OpenDate                    string      `json:"OpenDate"`
	OpenDatePublish             string      `json:"OpenDatePublish"`
	OpenDateAfterPublish        string      `json:"OpenDateAfterPublish"`
	OpenPrice                   float64     `json:"OpenPrice"`
	OpenPricePublish            float64     `json:"OpenPricePublish"`
	OpenPriceAfterPublish       float64     `json:"OpenPriceAfterPublish"`
	Dividends                   float64     `json:"Dividends"`
	TotalDividends              float64     `json:"TotalDividends"`
	DividendsPerShare           float64     `json:"DividendsPerShare"`
	TotalDRiPDividends          float64     `json:"TotalDRiPDividends"`
	Margin                      interface{} `json:"Margin"`
	TotalCredit                 interface{} `json:"TotalCredit"`
	PurchaseObligation          interface{} `json:"PurchaseObligation"`
	Income                      float64     `json:"Income"`
	CurrentPrice                float64     `json:"CurrentPrice"`
	CloseDate                   string      `json:"CloseDate"`
	ClosePrice                  float64     `json:"ClosePrice"`
	CurrentClosePrice           float64     `json:"CurrentClosePrice"`
	Gain                        float64     `json:"Gain"`
	TotalGain                   float64     `json:"TotalGain"`
	GainCurrency                float64     `json:"GainCurrency"`
	YTD                         interface{} `json:"YTD"`
	CapitalGainsYield           float64     `json:"CapitalGainsYield"`
	IsCustomGain                bool        `json:"IsCustomGain"`
	IsCustomAnnualizedGain      bool        `json:"IsCustomAnnualizedGain"`
	GainCustom                  interface{} `json:"GainCustom"`
	AnnualizedGainCustom        interface{} `json:"AnnualizedGainCustom"`
	OverallGain                 float64     `json:"OverallGain"`
	LastGain                    interface{} `json:"LastGain"`
	LastOpenPrice               interface{} `json:"LastOpenPrice"`
	LastOpenDate                interface{} `json:"LastOpenDate"`
	DollarGain                  float64     `json:"DollarGain"`
	TotalDollarGain             float64     `json:"TotalDollarGain"`
	AnnulizedGain               float64     `json:"AnnulizedGain"`
	HoldPeriod                  int         `json:"HoldPeriod"`
	DividendYield               float64     `json:"DividendYield"`
	ForwardDividendYield        float64     `json:"ForwardDividendYield"`
	IsCusomDividendYield        bool        `json:"IsCusomDividendYield"`
	IsCusomForwardDividendYield bool        `json:"IsCusomForwardDividendYield"`
	Subtrades                   []struct {
		ID              string `json:"$id"`
		SubtradeSetting struct {
			Id                        string      `json:"$id"`
			OpenPriceLink             interface{} `json:"OpenPriceLink"`
			OpenDateLink              interface{} `json:"OpenDateLink"`
			ClosePriceLink            interface{} `json:"ClosePriceLink"`
			CloseDateLink             interface{} `json:"CloseDateLink"`
			SymbolLink                interface{} `json:"SymbolLink"`
			Text1                     interface{} `json:"Text1"`
			Text2                     interface{} `json:"Text2"`
			Text3                     interface{} `json:"Text3"`
			Text4                     interface{} `json:"Text4"`
			Text5                     interface{} `json:"Text5"`
			TrailingStop              interface{} `json:"TrailingStop"`
			HardStop                  interface{} `json:"HardStop"`
			TSMinusDiv                interface{} `json:"TSMinusDiv"`
			SmartStop                 float64     `json:"SmartStop"`
			CloseBelowStop            interface{} `json:"CloseBelowStop"`
			CloseAboveStop            interface{} `json:"CloseAboveStop"`
			StopPriority              interface{} `json:"StopPriority"`
			StopPriorityValue         string      `json:"StopPriorityValue"`
			StopPriceValue            string      `json:"StopPriceValue"`
			StopPriorityName          string      `json:"StopPriorityName"`
			ApprovedBuy               bool        `json:"ApprovedBuy"`
			ApprovedSell              bool        `json:"ApprovedSell"`
			OpenApprovedStatus        int         `json:"OpenApprovedStatus"`
			CloseApprovedStatus       int         `json:"CloseApprovedStatus"`
			LegalApproverBuy          string      `json:"LegalApproverBuy"`
			LegalApproverSell         interface{} `json:"LegalApproverSell"`
			LegalNotes                string      `json:"LegalNotes"`
			ReasonForCustomOpenPrice  interface{} `json:"ReasonForCustomOpenPrice"`
			ReasonForCustomClosePrice interface{} `json:"ReasonForCustomClosePrice"`
			ReasonForCustomSymbol     string      `json:"ReasonForCustomSymbol"`
			EditorOpen                interface{} `json:"EditorOpen"`
			EditorClose               interface{} `json:"EditorClose"`
			IsDelisted                bool        `json:"IsDelisted"`
			Editor                    interface{} `json:"Editor"`
			Recommend                 interface{} `json:"Recommend"`
			Idss                      int         `json:"Id"`
		} `json:"SubtradeSetting"`
		CurrencyType                 int           `json:"CurrencyType"`
		CurrencySygn                 string        `json:"CurrencySygn"`
		CurrencyName                 string        `json:"CurrencyName"`
		HDSymbolID                   int           `json:"HDSymbolId"`
		SymbolID                     int           `json:"SymbolId"`
		CustomSymbol                 interface{}   `json:"CustomSymbol"`
		IsCustomSymbol               bool          `json:"IsCustomSymbol"`
		SymbolName                   string        `json:"SymbolName"`
		ExchangeMarket               string        `json:"ExchangeMarket"`
		Symbol                       string        `json:"Symbol"`
		OpenDate                     string        `json:"OpenDate"`
		TradeStatus                  int           `json:"TradeStatus"`
		RiskStatus                   interface{}   `json:"RiskStatus"`
		TaxStatus                    interface{}   `json:"TaxStatus"`
		IsCustomOpenPrice            bool          `json:"IsCustomOpenPrice"`
		IsCanadianPensionPlan        bool          `json:"IsCanadianPensionPlan"`
		OpenPrice                    float64       `json:"OpenPrice"`
		NonAdjOpenPrice              float64       `json:"NonAdjOpenPrice"`
		OpenValue                    float64       `json:"OpenValue"`
		DollarOpenValue              float64       `json:"DollarOpenValue"`
		OpenCurrency                 float64       `json:"OpenCurrency"`
		OpenPriceForSplit            interface{}   `json:"OpenPriceForSplit"`
		CloseDate                    string        `json:"CloseDate"`
		IsCustomClosePrice           bool          `json:"IsCustomClosePrice"`
		ClosePrice                   float64       `json:"ClosePrice"`
		CloseCurrency                float64       `json:"CloseCurrency"`
		CloseCustomCurrencyRates     interface{}   `json:"CloseCustomCurrencyRates"`
		TradeType                    int           `json:"TradeType"`
		OldShares                    float64       `json:"OldShares"`
		NewShares                    float64       `json:"NewShares"`
		SubtradeType                 int           `json:"SubtradeType"`
		TotalDividends               float64       `json:"TotalDividends"`
		DividendsPerShare            float64       `json:"DividendsPerShare"`
		TotalDRiPDividends           float64       `json:"TotalDRiPDividends"`
		Dividends                    float64       `json:"Dividends"`
		BuybackPrice                 interface{}   `json:"BuybackPrice"`
		CurrentPrice                 float64       `json:"CurrentPrice"`
		CurrentCurrency              float64       `json:"CurrentCurrency"`
		Gain                         interface{}   `json:"Gain"`
		YTD                          interface{}   `json:"YTD"`
		DollarGain                   interface{}   `json:"DollarGain"`
		TotalDollarGain              interface{}   `json:"TotalDollarGain"`
		GainCurrency                 float64       `json:"GainCurrency"`
		CapitalGainsYield            interface{}   `json:"CapitalGainsYield"`
		IsCustomGain                 bool          `json:"IsCustomGain"`
		IsCustomAnnualizedGain       bool          `json:"IsCustomAnnualizedGain"`
		GainCustom                   interface{}   `json:"GainCustom"`
		AnnualizedGainCustom         interface{}   `json:"AnnualizedGainCustom"`
		LastOpenPrice                interface{}   `json:"LastOpenPrice"`
		LastOpenDate                 interface{}   `json:"LastOpenDate"`
		AdjustBySplit                bool          `json:"AdjustBySplit"`
		CurrentClosePrice            float64       `json:"CurrentClosePrice"`
		CurrentCloseCurrency         float64       `json:"CurrentCloseCurrency"`
		CashAllocation               float64       `json:"CashAllocation"`
		CashAllocationPercent        float64       `json:"CashAllocationPercent"`
		OptionType                   interface{}   `json:"OptionType"`
		StockType                    interface{}   `json:"StockType"`
		StockStatus                  interface{}   `json:"StockStatus"`
		OptionStatus                 interface{}   `json:"OptionStatus"`
		Margin                       interface{}   `json:"Margin"`
		Action                       interface{}   `json:"Action"`
		Weight                       float64       `json:"Weight"`
		OpenWeight                   float64       `json:"OpenWeight"`
		Shares                       float64       `json:"Shares"`
		LastPriceUpdateDate          string        `json:"LastPriceUpdateDate"`
		ExpirationDate               interface{}   `json:"ExpirationDate"`
		ExDividendDate               interface{}   `json:"ExDividendDate"`
		StrikePrice                  interface{}   `json:"StrikePrice"`
		ExpirationAlertTriggered     bool          `json:"ExpirationAlertTriggered"`
		IsShowExpiredOptions         bool          `json:"IsShowExpiredOptions"`
		IsAutoGenerated              bool          `json:"IsAutoGenerated"`
		LowLowDate                   string        `json:"LowLowDate"`
		LowLowPrice                  float64       `json:"LowLowPrice"`
		LowCloseDate                 string        `json:"LowCloseDate"`
		LowClosePrice                float64       `json:"LowClosePrice"`
		HighHighDate                 string        `json:"HighHighDate"`
		HighHighPrice                float64       `json:"HighHighPrice"`
		HighCloseDate                string        `json:"HighCloseDate"`
		HighClosePrice               float64       `json:"HighClosePrice"`
		AdjLowLowDate                string        `json:"AdjLowLowDate"`
		AdjLowLowPrice               float64       `json:"AdjLowLowPrice"`
		AdjLowCloseDate              string        `json:"AdjLowCloseDate"`
		AdjLowClosePrice             float64       `json:"AdjLowClosePrice"`
		AdjHighHighDate              string        `json:"AdjHighHighDate"`
		AdjHighHighPrice             float64       `json:"AdjHighHighPrice"`
		AdjHighCloseDate             string        `json:"AdjHighCloseDate"`
		AdjHighClosePrice            float64       `json:"AdjHighClosePrice"`
		MaxGainDate                  string        `json:"MaxGainDate"`
		MaxGainPercent               float64       `json:"MaxGainPercent"`
		MinGainDate                  string        `json:"MinGainDate"`
		MinGainPercent               float64       `json:"MinGainPercent"`
		MaxPossibleHighGainDate      string        `json:"MaxPossibleHighGainDate"`
		MaxPossibleHighGainPercent   float64       `json:"MaxPossibleHighGainPercent"`
		PositionContent              []interface{} `json:"PositionContent"`
		CreationDate                 string        `json:"CreationDate"`
		DividendYield                interface{}   `json:"DividendYield"`
		ForwardDividendYield         interface{}   `json:"ForwardDividendYield"`
		IsCustomDividendYield        bool          `json:"IsCustomDividendYield"`
		IsCustomForwardDividendYield bool          `json:"IsCustomForwardDividendYield"`
		LatestAlertDate              interface{}   `json:"LatestAlertDate"`
		CGain                        interface{}   `json:"CGain"`
		CTotalGain                   interface{}   `json:"CTotalGain"`
		CDollarGain                  interface{}   `json:"CDollarGain"`
		CTotalDollarGain             interface{}   `json:"CTotalDollarGain"`
		CCapitalGainYiel             interface{}   `json:"CCapitalGainYiel"`
		CYTD                         interface{}   `json:"CYTD"`
		CLastGain                    interface{}   `json:"CLastGain"`
		CAnnGain                     interface{}   `json:"CAnnGain"`
		SharesPerContract            float64       `json:"SharesPerContract"`
		TotalGain                    interface{}   `json:"TotalGain"`
		TrailingStopPrice            interface{}   `json:"TrailingStopPrice"`
		SmartTrailingStopPrice       float64       `json:"SmartTrailingStopPrice"`
		HardStopPrice                interface{}   `json:"HardStopPrice"`
		TSMinusDivPrice              interface{}   `json:"TSMinusDivPrice"`
		HighPricePercent             float64       `json:"HighPricePercent"`
		LowPricePercent              interface{}   `json:"LowPricePercent"`
		IsExpiring                   bool          `json:"IsExpiring"`
		IsOpened                     bool          `json:"IsOpened"`
		IsLong                       bool          `json:"IsLong"`
		SubtradeTradeType            int           `json:"SubtradeTradeType"`
		MarketCap                    int64         `json:"MarketCap"`
		GicsSector                   string        `json:"GicsSector"`
		PriceEarnings                float64       `json:"PriceEarnings"`
		AverageVolume                int           `json:"AverageVolume"`
		PriceBook                    float64       `json:"PriceBook"`
		PriceRevenue                 float64       `json:"PriceRevenue"`
		IndustryName                 string        `json:"IndustryName"`
		Country                      string        `json:"Country"`
		GicsIndustry                 string        `json:"GicsIndustry"`
		SectorName                   string        `json:"SectorName"`
		UnderlyingStockOpenPrice     interface{}   `json:"UnderlyingStockOpenPrice"`
		UnderlyingStockCurrentPrice  interface{}   `json:"UnderlyingStockCurrentPrice"`
		MarginCR                     interface{}   `json:"MarginCR"`
		GainPercentCR                interface{}   `json:"GainPercentCR"`
		MarginIPM                    interface{}   `json:"MarginIPM"`
		GainPercentIPM               interface{}   `json:"GainPercentIPM"`
		HoldPeriod                   interface{}   `json:"HoldPeriod"`
		Idst                         int           `json:"Id"`
	} `json:"Subtrades"`
	LastUpdateDate           string      `json:"LastUpdateDate"`
	Weight                   float64     `json:"Weight"`
	IsFutures                bool        `json:"IsFutures"`
	IsDrip                   bool        `json:"IsDrip"`
	OpenWeight               float64     `json:"OpenWeight"`
	LastStatusChange         string      `json:"LastStatusChange"`
	Color                    string      `json:"Color"`
	PriceFluctuation         interface{} `json:"PriceFluctuation"`
	LastUpdateOpenStatus     string      `json:"LastUpdateOpenStatus"`
	LastUpdateCloseStatus    string      `json:"LastUpdateCloseStatus"`
	CreationDate             string      `json:"CreationDate"`
	LatestAlertDate          interface{} `json:"LatestAlertDate"`
	DollarOpenPrice          float64     `json:"DollarOpenPrice"`
	DollarCurrentClosePrice  float64     `json:"DollarCurrentClosePrice"`
	Rate                     float64     `json:"Rate"`
	RatePublish              float64     `json:"RatePublish"`
	RateAfterPublish         float64     `json:"RateAfterPublish"`
	SPXRate                  interface{} `json:"SPXRate"`
	DJIARate                 interface{} `json:"DJIARate"`
	RUTRate                  interface{} `json:"RUTRate"`
	SPXRatePublish           float64     `json:"SPXRatePublish"`
	DJIARatePublish          float64     `json:"DJIARatePublish"`
	RUTRatePublish           float64     `json:"RUTRatePublish"`
	SPXRateAfterPublish      float64     `json:"SPXRateAfterPublish"`
	DJIARateAfterPublish     float64     `json:"DJIARateAfterPublish"`
	RUTRateAfterPublish      float64     `json:"RUTRateAfterPublish"`
	StopPrice                interface{} `json:"StopPrice"`
	GUID                     string      `json:"Guid"`
	Imported                 bool        `json:"Imported"`
	HighCloseDate            interface{} `json:"HighCloseDate"`
	HighClosePrice           interface{} `json:"HighClosePrice"`
	AdjHighCloseDate         interface{} `json:"AdjHighCloseDate"`
	AdjHighClosePrice        interface{} `json:"AdjHighClosePrice"`
	CGain                    interface{} `json:"CGain"`
	CTotalGain               interface{} `json:"CTotalGain"`
	CDollarGain              interface{} `json:"CDollarGain"`
	CTotalDollarGain         interface{} `json:"CTotalDollarGain"`
	CCapitalGainYiel         interface{} `json:"CCapitalGainYiel"`
	CYTD                     interface{} `json:"CYTD"`
	CLastGain                interface{} `json:"CLastGain"`
	CAnnGain                 interface{} `json:"CAnnGain"`
	CValueCurrencyType       int         `json:"CValueCurrencyType"`
	CValue                   float64     `json:"CValue"`
	TrailingStopPrice        interface{} `json:"TrailingStopPrice"`
	HardStopPrice            interface{} `json:"HardStopPrice"`
	ExchangeMarket           string      `json:"ExchangeMarket"`
	RiskStatus               interface{} `json:"RiskStatus"`
	TaxStatus                interface{} `json:"TaxStatus"`
	TradeStatus              int         `json:"TradeStatus"`
	CostBasis                interface{} `json:"CostBasis"`
	CostBasisForOne          interface{} `json:"CostBasisForOne"`
	IsOpened                 bool        `json:"IsOpened"`
	IsCanadianPensionPlan    interface{} `json:"IsCanadianPensionPlan"`
	Currency                 int         `json:"Currency"`
	PurchaseObligationXML    float64     `json:"PurchaseObligationXML"`
	MarginXML                float64     `json:"MarginXML"`
	OpeningCreditXML         float64     `json:"OpeningCreditXML"`
	OpeningReturnOnMarginXML float64     `json:"OpeningReturnOnMarginXML"`
	CurrentXML               float64     `json:"CurrentXML"`
	CurrentReturnXML         float64     `json:"CurrentReturnXML"`
	ActionStatusXML          string      `json:"ActionStatusXML"`
	CashAllocationPercent    float64     `json:"CashAllocationPercent"`
	CashAllocation           float64     `json:"CashAllocation"`
	Value                    float64     `json:"Value"`
	DownsideCurrentPrice     float64     `json:"DownsideCurrentPrice"`
	DownsideClosePrice       float64     `json:"DownsideClosePrice"`
	TotalIncome              float64     `json:"TotalIncome"`
	PositionTypeTitle        interface{} `json:"PositionTypeTitle"`
	GicsSector               string      `json:"GicsSector"`
	MarketCap                int64       `json:"MarketCap"`
	PriceEarnings            float64     `json:"PriceEarnings"`
	AverageVolume            int         `json:"AverageVolume"`
	PriceBook                float64     `json:"PriceBook"`
	PriceRevenue             float64     `json:"PriceRevenue"`
	IndustryName             string      `json:"IndustryName"`
	Country                  string      `json:"Country"`
	GicsIndustry             string      `json:"GicsIndustry"`
	SectorName               string      `json:"SectorName"`
	MarginCR                 interface{} `json:"MarginCR"`
	GainPercentCR            interface{} `json:"GainPercentCR"`
	CapitalAtRisk            interface{} `json:"CapitalAtRisk"`
	CapitalAtRiskReturn      interface{} `json:"CapitalAtRiskReturn"`
	AnnualizedReturnOnCaR    interface{} `json:"AnnualizedReturnOnCaR"`
	Idz                      int         `json:"Id"`
}

type Position struct {
	UID         int    `json:"id"`
	Name        string `json:"name"`
	Affiliateid int    `json:"affiliateid"`
	Type        string `json:"type"`
	Data        []PositionDetail
}
